In [50]:
#NN Surrogate model class
import injector_surrogate_quads
from injector_surrogate_quads import *
import physics_gp

sys.path.append('../configs')
#Sim reference point to optimize around
from ref_config import ref_point

#Pytorch 
import numpy as np
import torch
import transformer
import gpytorch
import botorch 

# BO for Minimizing Emittance

In [28]:
#load injector model
Model = Surrogate_NN()

Model.load_saved_model(model_path = '../models/', \
                       model_name = 'model_OTR2_NA_rms_emit_elu_2021-07-27T19_54_57-07_00')
Model.load_scaling()
Model.take_log_out = False

## Objective Function

In [29]:
#convert to machine units
ref_point = Model.sim_to_machine(np.asarray(ref_point))

#input params: solenoid and quads to vary 
opt_var_names = ['SOL1:solenoid_field_scale','SQ01:b1_gradient','CQ01:b1_gradient']

#output params: emittance in transverse plane (x & y)
opt_out_names = ['norm_emit_x','norm_emit_y']

def evaluate(varx,vary,varz): 

    #make input array of length model_in_list (inputs model takes)
    x_in = np.empty((1,len(Model.model_in_list)))

    #fill in reference point around which to optimize
    x_in[:,:] = np.asarray(ref_point[0])

    #set solenoid, SQ, CQ to values from optimization step
    x_in[:, Model.loc_in[opt_var_names[0]]] = varx
    x_in[:, Model.loc_in[opt_var_names[1]]] = vary
    x_in[:, Model.loc_in[opt_var_names[2]]] = varz

    #output predictions
    y_out = Model.pred_machine_units(x_in) 

    return -1*objective(y_out)[0]


def objective(y_out):
    
    #output is geometric emittance in transverse plane
    out1 = y_out[:,Model.loc_out['norm_emit_x']] #grab norm_emit_x out of the model
    out2 = y_out[:,Model.loc_out['norm_emit_y']] #grab norm_emit_y out of the model
       
    return np.sqrt(out1*out2)/1e-6 # in um units

## Gaussian Regression & Acquisition Function

In [41]:
def get_BO_point(x, f, bounds, beta=2.5, phys=True):
    """

    function that trains a GP model of data and returns the next observation point using UCB
    D is input space dimensionality
    N is number of samples

    :param x: input points data, torch.tensor, shape (N,D)
    :param f: output point data, torch.tensor, shape (N,1)
    :param bounds: input space bounds, torch.tensor, shape (2,D)
    :param precision: precision matrix used for RBF kernel (must be PSD), torch.tensor, (D,D)
    :param beta: UCB optimization parameter, float
    :return x_candidate, model: next observation point and gp model w/observations
    """
    
    likelihood = gpytorch.likelihoods.GaussianLikelihood()
    
    if phys == True:
        gp = physics_gp.PhysicsExactGPModel(x, f.flatten(), likelihood, precision)
    else:
        gp = botorch.models.SingleTaskGP(x, f, likelihood)
        
    mll = gpytorch.mlls.ExactMarginalLogLikelihood(gp.likelihood, gp)
    
    # fit GP hyperparameters
    #print('training hyperparameters')
    botorch.fit.fit_gpytorch_model(mll)

    # do UCB acquisition
    #print('optimizing acquisition function')
    UCB = botorch.acquisition.UpperConfidenceBound(gp, beta=beta)
    candidate, acq_value = botorch.optim.optimize_acqf(UCB,
                                                       bounds=bounds,
                                                       q=1,
                                                       num_restarts=20,#5
                                                       raw_samples=20)
    return candidate, gp

## Set up initial training samples

In [48]:
#specify bounds
bounds = {'varx': (0.44, 0.55),
          'vary': (-0.02, 0.02),
          'varz': (-0.02, 0.02)
         }

tbounds = torch.tensor([[bounds['varx'][0], bounds['varx'][1]],[bounds['vary'][0], 
                         bounds['vary'][1]], [bounds['varz'][0], bounds['varz'][1]]])

#print(bounds['varx'][0])
#print(tbounds)

diff = {'varx': bounds['varx'][1] - bounds['varx'][0],
        'vary': bounds['vary'][1] - bounds['vary'][0],
        'varz': bounds['varz'][1] - bounds['varz'][0]
       }

#create initial samples within specified bounds
n_samples = 5
train_x = torch.zeros((5, 3)) 
for i in range(3):
    train_x[:,i] = torch.as_tensor(np.random.uniform(tbounds[i,0],tbounds[i,1],(n_samples,)))
#train_x = torch.as_tensor(train_x).type(torch.FloatTensor)

"""
train_x = torch.rand(n_samples,3) 
train_x[:,0] = train_x[:,0] * diff['varx'] + bounds['varx'][0]
train_x[:,1] = train_x[:,1] * diff['vary'] + bounds['vary'][0]
train_x[:,2] = train_x[:,2] * diff['varz'] + bounds['varz'][0]
""" 
print(train_x)

train_y = torch.tensor([evaluate(vars[0], vars[1], vars[2]) for vars in train_x]).reshape(-1,1)
print(train_y)


#transformer 
transformer_x = transformer.Transformer(tbounds.transpose(0,1), transform_type = 'normalize')
print(transformer_x.mins)
print(transformer_x.maxs)
normed_train_x = transformer_x.forward(train_x)

transformer_y = transformer.Transformer(train_y, transform_type = 'standardize') 
normed_train_y = transformer_y.forward(train_y)

""" 
#create initial model
gp = SingleTaskGP(normed_train_x, normed_train_y)
mll = ExactMarginalLogLikelihood(gp.likelihood, gp)
fit_gpytorch_model(mll);
"""

tensor([[ 0.4525, -0.0182, -0.0077],
        [ 0.4477,  0.0031,  0.0151],
        [ 0.4621,  0.0112, -0.0132],
        [ 0.5076, -0.0099,  0.0199],
        [ 0.5312, -0.0026,  0.0143]])
tensor([[-1.9490],
        [-1.9504],
        [-1.0072],
        [-2.5965],
        [-3.7859]])
[ 0.44 -0.02 -0.02]
[0.55 0.02 0.02]


' \n#create initial model\ngp = SingleTaskGP(normed_train_x, normed_train_y)\nmll = ExactMarginalLogLikelihood(gp.likelihood, gp)\nfit_gpytorch_model(mll);\n'

## Bayesian Optimization

In [49]:
n_steps = 30
for i in range(n_steps):
    if i > 10:
        phys_l = True
        
    bounds = torch.cat((torch.zeros(1,3), torch.ones(1,3)), 0)
    x_new, model = get_BO_point(normed_train_x, normed_train_y, bounds=bounds, phys = False)
    
    train_x = torch.cat((train_x, transformer_x.backward(x_new)))
    normed_train_x = transformer_x.forward(train_x)
    
    new_y = torch.tensor(evaluate(train_x[-1,0], train_x[-1,1], train_x[-1,2])).reshape(1,1)
    train_y = torch.cat((train_y, new_y))
    normed_train_y = transformer_y.forward(train_y)
    
    train_x = train_x.type(torch.FloatTensor)
    train_y = train_y.type(torch.FloatTensor)
    
    print("iteration        target         varx         vary         varz")
    print(f'{i+1}              {train_y[-1][0]:.5f}      {train_x[-1][0]:.5f}      {train_x[-1][1]:.5f}      {train_x[-1][2]:.5f}')
    print(f'global max = {torch.max(train_y)})

iteration        target         varx         vary         varz
1              -1.98142      0.44000      0.00555      -0.02000
tensor(-1.0072)
iteration        target         varx         vary         varz
2              -1.19703      0.46154      0.02000      -0.00585
tensor(-1.0072)
iteration        target         varx         vary         varz
3              -0.69682      0.47823      0.01910      -0.01771
tensor(-0.6968)
iteration        target         varx         vary         varz
4              -1.31261      0.48971      0.00922      -0.01773
tensor(-0.6968)
iteration        target         varx         vary         varz
5              -0.96412      0.46409      0.02000      -0.02000
tensor(-0.6968)
iteration        target         varx         vary         varz
6              -0.71521      0.48108      0.02000      -0.01025
tensor(-0.6968)
iteration        target         varx         vary         varz
7              -0.65580      0.47522      0.01488      -0.01182
tensor(-0.6558)

In [ ]:
"""
#define acquisition function
from botorch.acquisition.analytic import UpperConfidenceBound, ExpectedImprovement
from botorch.optim import optimize_acqf

#optimize
n_steps = 45
for i in range(n_steps):
    #best_normed_y = torch.max(normed_train_y)
    UCB = UpperConfidenceBound(gp, beta=2.5)
    #EI = ExpectedImprovement(gp, best_normed_y)

    bounds = torch.cat((torch.zeros(1,3), torch.ones(1,3)), 0)
    candidate, acq_value = optimize_acqf(UCB, bounds = bounds, num_restarts = 20, q = 1, raw_samples = 20)

    train_x = torch.cat((train_x, transformer_x.backward(candidate)))
    normed_train_x = transformer_x.forward(train_x)

    new_y = torch.tensor(evaluate(train_x[-1][0], train_x[-1][1], train_x[-1][2])).reshape(1,1)
    train_y = torch.cat((train_y, new_y))
    
    print("iteration        target         varx         vary         varz")
    print(f'{i+1}              {train_y[-1][0]:.5f}      {train_x[-1][0]:.5f}      {train_x[-1][1]:.5f}      {train_x[-1][2]:.5f}')
    print(torch.max(train_y))
    
    transformer_y = transformer.Transformer(train_y, 'standardize')
    normed_train_y = transformer_y.forward(train_y)

    gp = SingleTaskGP(normed_train_x, normed_train_y)
    mll = ExactMarginalLogLikelihood(gp.likelihood, gp)
    fit_gpytorch_model(mll);
"""